### PR TITLE
Add ESP32-S3-Box-3 support

### PR DESCRIPTION
**Pull request by stintel**

### CODE REVIEW

**Comment by paulgrove** [comment]
Wow very cool! I'm going to try this out as soon as I can!

**Comment by stintel** [comment]
Should be able to flash via https://feature-esp32-s3-box-3.willow-web-flash.pages.dev/

**Comment by paulgrove** [comment]
Great, I'll do that and I'll try building it myself, I want to make sure I got everything working in my build environment.

**Comment by kristiankielhofner** [comment]
Torture testing results:

988/1000 HA action_done
2000/2000 AUDIO_REC_WAKEUP

Ship it!

**Review by kristiankielhofner — APPROVED** [review]

**Pull request merged**
