### PR TITLE
Timezone changes

### PR DESCRIPTION
**Pull request by mineshaftgap**
- Name docker container for easier access by other sessions
- Break out timezone config to separate file
- Very explicit timezone selection for kconfig
- Add tzdata to docker image for generating timezone data for kconfig
- Generate timezone data for kconfig in util.sh

### CODE REVIEW

**Comment by mineshaftgap** [comment]
I know that this PR makes the timezone config list very long, but I ended up going down quite a deep rabbit hole in order to have very proper timezone configuration.

The current UTC+5 default along with Espressif's timezone code examples over simplifies when it comes to things like daylight savings.

Since the timezone data is perpetually updated, I added a command to util.sh to generate new timezone data.

**Comment by stintel** [comment]
As the data can be generated with utils.sh, can we not just drop the file from git and when we run build, check if the file exists, and generate it?

**Comment by mineshaftgap** [comment]
We can do that as long as we make it mandatory part of the build, I did not do that.

**Comment by mineshaftgap** [comment]
@kristiankielhofner Totally understand that the build process is very temporary. That is one of the reasons I did not make  generating the time zone part of the build but instead something that can be run optionally when needed putting it in util.sh for any build automation.

The current issue that I was trying to make sure did not trip people up is that right now the existing implementation is faulty.
1. Configuring a timezone is exposed to the very same beginner user in the same area that they are told to change currently in the README.md
2. There is no documentation in the README.md, wiki or kconfig for the user what this value should be.
3. The default value is `UTC+5` which is essentially Chicago's timezone right now, but does not take into account daylight savings.
4. A user who uses the default as an example might not know it is suppose to be Chicago but clever enough to use what they think of as their current timezone, say `UTC-7`, this however would be wrong (by 14 hours) as per [tzset](https://man7.org/linux/man-pages/man3/tzset.3.html) docs:
   - "The offset is positive if the local timezone is west of the Prime Meridian and negative if it is east."
5. A user unfamiliar with tzdata and the POSIX timezone string format might mistakenly use `PST` which is not correct. This also would again be wrong and it would fall back to `UTC` according to [tzset](https://man7.org/linux/man-pages/man3/tzset.3.html) docs:
   - "If the TZ variable does appear in the environment, but its value is empty, or its value cannot be interpreted using any of the formats specified below, then Coordinated Universal Time (UTC) is used."
6. Any use of local time by a user not knowing the unintuitive offset or [complex POSIX format](https://github.com/nayarsystems/posix_tz_db/blob/master/zones.csv) results in any local time being displayed incorrectly

I am not trying to argue to have this included, but to show the problems of the current situation. I would highly encourage there to be a documentation in both the README.md and the wiki on this issue. I am happy to submit a documentation PR discussing this instead of a temporary fix if it would be acceptable.

**Comment by kristiankielhofner** [comment]
- We don't currently use the time for anything other than serial monitor logging lines. We're planning on addressing this at the point the display presents the time to the user in some fashion.
- The approach I outlined would not expose the POSIX string to the user. WIS would take a friendly name like 'America/Chicago' (or similar) that's exposed in a WIS hosted web UI (or other interface), use tzdata on the machine running WIS to map to POSIX string, and then that's what we would return to the device.

**Comment by mineshaftgap** [comment]
Ok, I am closing this PR, will keep the code to display date & time on my fork, and not submit as a PR.

**Pull request closed without merging**
